name: SSH test

on: 
  pull_request:
    types: [opened, edited, reopened]
env:
  IMAGE_NAME: request-bin-api
  IMAGE_DIR: ./server
  DOCKER_USER: sjbabadi

jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v1
      - name: Build api image
        run: docker build -t ${IMAGE_NAME} ./server
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: sjbabadi
            password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish to registry
        run: |
          docker tag ${IMAGE_NAME} ${DOCKER_USER}/${IMAGE_NAME}
          docker push ${DOCKER_USER}/${IMAGE_NAME}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-18.04
    steps:
      - name: Executing remote script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd request-bin
            docker-compose down
            docker-compose up --build -d

          